services:
  postgres:
    image: postgres:13
    container_name: postgres-concert
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: defaultdb
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api-concert
    environment:
      DATABASE_URL: postgresql://admin:admin@postgres:5432/defaultdb
    depends_on:
      - postgres
    ports:
      - '5000:5000'
    command: sh -c "npx prisma migrate dev && node dist/main.js"

volumes:
  postgres_data:

networks:
  host:
    driver: bridge
