version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: postgres-concert
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: defaultdb
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - service-net

volumes:
  rabbitmq_data:
  postgres_data:

networks:
  service-net:
